package com.comp9323.RestAPI.Beans;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by timta on 11/09/2017.
 * Autogenerated using jsonschema2pojo
 */

public class EventBean {

    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("name")
    @Expose
    private String name;
    @SerializedName("description")
    @Expose
    private String description;
    @SerializedName("start_time")
    @Expose
    private String startTime;
    @SerializedName("facebook_id")
    @Expose
    private String facebookId;
    @SerializedName("start_date")
    @Expose
    private String startDate;
    @SerializedName("end_date")
    @Expose
    private String endDate;
    @SerializedName("end_time")
    @Expose
    private String endTime;
    @SerializedName("place_name")
    @Expose
    private String placeName;
    @SerializedName("city")
    @Expose
    private String city;
    @SerializedName("country")
    @Expose
    private String country;
    @SerializedName("latitude")
    @Expose
    private String latitude;
    @SerializedName("longitude")
    @Expose
    private String longitude;
    @SerializedName("state")
    @Expose
    private String state;
    @SerializedName("street")
    @Expose
    private String street;
    @SerializedName("zip")
    @Expose
    private String zip;
    @SerializedName("cover_id")
    @Expose
    private String coverId;
    @SerializedName("source_url")
    @Expose
    private String sourceUrl;

    public EventBean(Integer id, String name, String description, String startTime, String facebookId, String startDate, String endDate, String endTime, String placeName, String city, String country, String latitude, String longitude, String state, String street, String zip, String coverId, String sourceUrl) {
        super();
        this.id = id;
        this.name = name;
        this.description = description;
        this.startTime = startTime;
        this.facebookId = facebookId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.endTime = endTime;
        this.placeName = placeName;
        this.city = city;
        this.country = country;
        this.latitude = latitude;
        this.longitude = longitude;
        this.state = state;
        this.street = street;
        this.zip = zip;
        this.coverId = coverId;
        this.sourceUrl = sourceUrl;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getFacebookId() {
        return facebookId;
    }

    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getPlaceName() {
        return placeName;
    }

    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getCoverId() {
        return coverId;
    }

    public void setCoverId(String coverId) {
        this.coverId = coverId;
    }

    public String getSourceUrl() {
        return sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    public String getEventTime() {
        DateFormat df = new SimpleDateFormat("HH:dd:ss");
        Date startTime;
        Date endTime;
        try {
            startTime = df.parse(this.getStartTime());
        } catch (ParseException e) {

        }
        //String startTime = this.getStartTime().substring(0, this.getStartTime().length()-3);
        String endTime = this.getEndTime().substring(0, this.getEndTime().length()-3);
        String time = startTime + " to " + endTime;
        String date;
        if (this.getStartDate().equals(this.getEndDate())) {
            date = this.getStartDate();
        } else {
            date = this.getStartDate() + " to " + this.getEndDate();
        }
        return date + ", " + time;
    }
}
