package com.comp9323.data.beans;

import android.util.Log;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by timta on 11/09/2017.
 * Autogenerated using jsonschema2pojo
 */


import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * A Class that represent the Event Object that used in the application
 * This Class acts as bean class the allowing converting Database tuple into java Object
 * @Field Integer id            Unique identify from the Database
 * @Field String name           Event title or given name
 * @Field String description    Description of the Event
 * @Field String startTime      Event starting time
 * @Field String facebookId     Unique identify from the External resource
 * @Field String startDate      Event starting date
 * @Field String endDate        Event ending date
 * @Field String endTime        Event ending time
 * @Field String placeName      Event holding location
 * @Field String city           Event holding city
 * @Field String country        Event holding country
 * @Field String latitude       Event holding GPS latitude
 * @Field String longitude      Event holding GPS longitude
 * @Field String state          Event holding state
 * @Field String street         Event holding street
 * @Field String zip            Event holding zip
 * @Field String coverId        Facebook photo URI
 * @Field String sourceUrl      A URL to the original post
 * @Field String rating         An In-app rating from this app user
 * @Field String createdBy     creator of this food deal, or resource location
 */
public class Event {

    @SerializedName("id")
    @Expose
    private Integer id;
    @SerializedName("name")
    @Expose
    private String name;
    @SerializedName("description")
    @Expose
    private String description;
    @SerializedName("start_time")
    @Expose
    private String startTime;
    @SerializedName("facebook_id")
    @Expose
    private String facebookId;
    @SerializedName("start_date")
    @Expose
    private String startDate;
    @SerializedName("end_date")
    @Expose
    private String endDate;
    @SerializedName("end_time")
    @Expose
    private String endTime;
    @SerializedName("place_name")
    @Expose
    private String placeName;
    @SerializedName("city")
    @Expose
    private String city;
    @SerializedName("country")
    @Expose
    private String country;
    @SerializedName("latitude")
    @Expose
    private String latitude;
    @SerializedName("longitude")
    @Expose
    private String longitude;
    @SerializedName("state")
    @Expose
    private String state;
    @SerializedName("street")
    @Expose
    private String street;
    @SerializedName("zip")
    @Expose
    private String zip;
    @SerializedName("cover_id")
    @Expose
    private String coverId;
    @SerializedName("source_url")
    @Expose
    private String sourceUrl;
    @SerializedName("rating")
    @Expose
    private String rating;
    @SerializedName("created_by")
    @Expose
    private String createdBy;

    public Event() {}

    public Event(String name, String location, String startDate, String endDate, String startTime,
                 String endTime, String description, String createdBy) {
        this.name = name;
        this.placeName = location;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startTime = startTime;
        this.endTime = endTime;
        this.description = description;
        this.createdBy = createdBy;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getFacebookId() {
        return facebookId;
    }

    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getPlaceName() {
        return placeName;
    }

    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getCoverId() {
        return coverId;
    }

    public void setCoverId(String coverId) {
        this.coverId = coverId;
    }

    public String getSourceUrl() {
        return sourceUrl;
    }

    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    public String getRating() {
        return rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Create readable time String from time and date detail in the Event
     * @return TimeString that ready to display on screen
     */
    public String getEventTime() {
        DateFormat oTimeFormat = new SimpleDateFormat("HH:mm");
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat nTimeFormat = new SimpleDateFormat("hh:mma");
        DateFormat nDateFormat = new SimpleDateFormat("MMM d");

        try {
            Date sDate = oDateFormat.parse(this.getStartDate());
            Date eDate = oDateFormat.parse(this.getEndDate());
            Date sTime = oTimeFormat.parse(this.getStartTime());
            Date eTime = oTimeFormat.parse(this.getEndTime());

            if (this.getStartDate().equals(this.getEndDate())) {
                return (nDateFormat.format(sDate) + ", " + nTimeFormat.format(sTime)
                        + " - " + nTimeFormat.format(eTime));
            } else {
                return (nDateFormat.format(sDate) + ", " + nTimeFormat.format(sTime)
                        + " - " + nDateFormat.format(eDate) + ", " + nTimeFormat.format(eTime));
            }
        } catch (ParseException e) {
            Log.d("Event Date Convert", "Parse Failed");
            return "";
        }
    }

}
